/*
 * Sonarr
 *
 * Sonarr API docs - The v3 API docs apply to both v3 and v4 versions of Sonarr. Some functionality may only be available in v4 of the Sonarr application.
 *
 * The version of the OpenAPI document: 3.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Sonarr.OpenAPI.Client.OpenAPIDateConverter;

namespace Sonarr.OpenAPI.Model
{
    /// <summary>
    /// ReleaseEpisodeResource
    /// </summary>
    [DataContract(Name = "ReleaseEpisodeResource")]
    public partial class ReleaseEpisodeResource : IEquatable<ReleaseEpisodeResource>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ReleaseEpisodeResource" /> class.
        /// </summary>
        /// <param name="id">id.</param>
        /// <param name="seasonNumber">seasonNumber.</param>
        /// <param name="episodeNumber">episodeNumber.</param>
        /// <param name="absoluteEpisodeNumber">absoluteEpisodeNumber.</param>
        /// <param name="title">title.</param>
        public ReleaseEpisodeResource(int id = default(int), int seasonNumber = default(int), int episodeNumber = default(int), int? absoluteEpisodeNumber = default(int?), string title = default(string))
        {
            this.Id = id;
            this.SeasonNumber = seasonNumber;
            this.EpisodeNumber = episodeNumber;
            this.AbsoluteEpisodeNumber = absoluteEpisodeNumber;
            this.Title = title;
        }

        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [DataMember(Name = "id", EmitDefaultValue = false)]
        public int Id { get; set; }

        /// <summary>
        /// Gets or Sets SeasonNumber
        /// </summary>
        [DataMember(Name = "seasonNumber", EmitDefaultValue = false)]
        public int SeasonNumber { get; set; }

        /// <summary>
        /// Gets or Sets EpisodeNumber
        /// </summary>
        [DataMember(Name = "episodeNumber", EmitDefaultValue = false)]
        public int EpisodeNumber { get; set; }

        /// <summary>
        /// Gets or Sets AbsoluteEpisodeNumber
        /// </summary>
        [DataMember(Name = "absoluteEpisodeNumber", EmitDefaultValue = true)]
        public int? AbsoluteEpisodeNumber { get; set; }

        /// <summary>
        /// Gets or Sets Title
        /// </summary>
        [DataMember(Name = "title", EmitDefaultValue = true)]
        public string Title { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class ReleaseEpisodeResource {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  SeasonNumber: ").Append(SeasonNumber).Append("\n");
            sb.Append("  EpisodeNumber: ").Append(EpisodeNumber).Append("\n");
            sb.Append("  AbsoluteEpisodeNumber: ").Append(AbsoluteEpisodeNumber).Append("\n");
            sb.Append("  Title: ").Append(Title).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as ReleaseEpisodeResource);
        }

        /// <summary>
        /// Returns true if ReleaseEpisodeResource instances are equal
        /// </summary>
        /// <param name="input">Instance of ReleaseEpisodeResource to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ReleaseEpisodeResource input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Id == input.Id ||
                    this.Id.Equals(input.Id)
                ) && 
                (
                    this.SeasonNumber == input.SeasonNumber ||
                    this.SeasonNumber.Equals(input.SeasonNumber)
                ) && 
                (
                    this.EpisodeNumber == input.EpisodeNumber ||
                    this.EpisodeNumber.Equals(input.EpisodeNumber)
                ) && 
                (
                    this.AbsoluteEpisodeNumber == input.AbsoluteEpisodeNumber ||
                    (this.AbsoluteEpisodeNumber != null &&
                    this.AbsoluteEpisodeNumber.Equals(input.AbsoluteEpisodeNumber))
                ) && 
                (
                    this.Title == input.Title ||
                    (this.Title != null &&
                    this.Title.Equals(input.Title))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                hashCode = hashCode * 59 + this.Id.GetHashCode();
                hashCode = hashCode * 59 + this.SeasonNumber.GetHashCode();
                hashCode = hashCode * 59 + this.EpisodeNumber.GetHashCode();
                if (this.AbsoluteEpisodeNumber != null)
                    hashCode = hashCode * 59 + this.AbsoluteEpisodeNumber.GetHashCode();
                if (this.Title != null)
                    hashCode = hashCode * 59 + this.Title.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        public IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
