/*
 * Radarr
 *
 * Radarr API docs
 *
 * The version of the OpenAPI document: 3.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Radarr.OpenAPI.Client.OpenAPIDateConverter;

namespace Radarr.OpenAPI.Model
{
    /// <summary>
    /// MovieFileListResource
    /// </summary>
    [DataContract(Name = "MovieFileListResource")]
    public partial class MovieFileListResource : IEquatable<MovieFileListResource>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="MovieFileListResource" /> class.
        /// </summary>
        /// <param name="movieFileIds">movieFileIds.</param>
        /// <param name="languages">languages.</param>
        /// <param name="quality">quality.</param>
        /// <param name="edition">edition.</param>
        /// <param name="releaseGroup">releaseGroup.</param>
        /// <param name="sceneName">sceneName.</param>
        /// <param name="indexerFlags">indexerFlags.</param>
        public MovieFileListResource(List<int> movieFileIds = default(List<int>), List<Language> languages = default(List<Language>), QualityModel quality = default(QualityModel), string edition = default(string), string releaseGroup = default(string), string sceneName = default(string), int? indexerFlags = default(int?))
        {
            this.MovieFileIds = movieFileIds;
            this.Languages = languages;
            this.Quality = quality;
            this.Edition = edition;
            this.ReleaseGroup = releaseGroup;
            this.SceneName = sceneName;
            this.IndexerFlags = indexerFlags;
        }

        /// <summary>
        /// Gets or Sets MovieFileIds
        /// </summary>
        [DataMember(Name = "movieFileIds", EmitDefaultValue = true)]
        public List<int> MovieFileIds { get; set; }

        /// <summary>
        /// Gets or Sets Languages
        /// </summary>
        [DataMember(Name = "languages", EmitDefaultValue = true)]
        public List<Language> Languages { get; set; }

        /// <summary>
        /// Gets or Sets Quality
        /// </summary>
        [DataMember(Name = "quality", EmitDefaultValue = false)]
        public QualityModel Quality { get; set; }

        /// <summary>
        /// Gets or Sets Edition
        /// </summary>
        [DataMember(Name = "edition", EmitDefaultValue = true)]
        public string Edition { get; set; }

        /// <summary>
        /// Gets or Sets ReleaseGroup
        /// </summary>
        [DataMember(Name = "releaseGroup", EmitDefaultValue = true)]
        public string ReleaseGroup { get; set; }

        /// <summary>
        /// Gets or Sets SceneName
        /// </summary>
        [DataMember(Name = "sceneName", EmitDefaultValue = true)]
        public string SceneName { get; set; }

        /// <summary>
        /// Gets or Sets IndexerFlags
        /// </summary>
        [DataMember(Name = "indexerFlags", EmitDefaultValue = true)]
        public int? IndexerFlags { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class MovieFileListResource {\n");
            sb.Append("  MovieFileIds: ").Append(MovieFileIds).Append("\n");
            sb.Append("  Languages: ").Append(Languages).Append("\n");
            sb.Append("  Quality: ").Append(Quality).Append("\n");
            sb.Append("  Edition: ").Append(Edition).Append("\n");
            sb.Append("  ReleaseGroup: ").Append(ReleaseGroup).Append("\n");
            sb.Append("  SceneName: ").Append(SceneName).Append("\n");
            sb.Append("  IndexerFlags: ").Append(IndexerFlags).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as MovieFileListResource);
        }

        /// <summary>
        /// Returns true if MovieFileListResource instances are equal
        /// </summary>
        /// <param name="input">Instance of MovieFileListResource to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(MovieFileListResource input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.MovieFileIds == input.MovieFileIds ||
                    this.MovieFileIds != null &&
                    input.MovieFileIds != null &&
                    this.MovieFileIds.SequenceEqual(input.MovieFileIds)
                ) && 
                (
                    this.Languages == input.Languages ||
                    this.Languages != null &&
                    input.Languages != null &&
                    this.Languages.SequenceEqual(input.Languages)
                ) && 
                (
                    this.Quality == input.Quality ||
                    (this.Quality != null &&
                    this.Quality.Equals(input.Quality))
                ) && 
                (
                    this.Edition == input.Edition ||
                    (this.Edition != null &&
                    this.Edition.Equals(input.Edition))
                ) && 
                (
                    this.ReleaseGroup == input.ReleaseGroup ||
                    (this.ReleaseGroup != null &&
                    this.ReleaseGroup.Equals(input.ReleaseGroup))
                ) && 
                (
                    this.SceneName == input.SceneName ||
                    (this.SceneName != null &&
                    this.SceneName.Equals(input.SceneName))
                ) && 
                (
                    this.IndexerFlags == input.IndexerFlags ||
                    (this.IndexerFlags != null &&
                    this.IndexerFlags.Equals(input.IndexerFlags))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.MovieFileIds != null)
                    hashCode = hashCode * 59 + this.MovieFileIds.GetHashCode();
                if (this.Languages != null)
                    hashCode = hashCode * 59 + this.Languages.GetHashCode();
                if (this.Quality != null)
                    hashCode = hashCode * 59 + this.Quality.GetHashCode();
                if (this.Edition != null)
                    hashCode = hashCode * 59 + this.Edition.GetHashCode();
                if (this.ReleaseGroup != null)
                    hashCode = hashCode * 59 + this.ReleaseGroup.GetHashCode();
                if (this.SceneName != null)
                    hashCode = hashCode * 59 + this.SceneName.GetHashCode();
                if (this.IndexerFlags != null)
                    hashCode = hashCode * 59 + this.IndexerFlags.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        public IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
